#!/bin/bash

[ -z "$1" ] && {
    echo "Not enough arguments! Expects $0 'texfile'"
    exit 1
}

# echo "$1.tex"
mkdir -p .log

echo "'$1'"
# if [[ 'test.tex' =~ '\.tex$' ]]; then echo Hey; fi

echo ${1::-4}
if [ "${1: -4}" == ".tex" ]; then  
    echo Hey

    #name=$(printf '%s' "$1" | rev | cut -d'.' -f2- | rev)
    name=${1::-4}
else 
    name="$1"
fi

# pdflatex -output-directory=".log"  -synctex=1 -interaction=nonstopmode "$1.tex"
pdflatex -output-directory=".log" -interaction=nonstopmode "$name.tex"
mv ".log/$name.pdf" .



