#!/bin/sh
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
#           Depricated
# `./prompt "Do you want to shutdown?" "shutdown -h now"`
# OR better: 
# `./prompt "Do you want to shutdown?" \
#       && shutdown -h now || echo "Dose not turn off"`

# Custimisable and default sould read from a lang file
YES="Yes"; NO="No" 

_dmenu() { dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray; }

[ "$(printf "$NO\\n$YES" | _dmenu "$1" )" = "$YES" ] || exit 1 
[ -z "$2" ] || (echo "$2" | bash)  # Depricated 

