#!/bin/sh
# For example:
# `./prompt "Do you want to shutdown?" \
#       && shutdown -h now || echo "Dose not turn off"`

YES="Yes"; NO="No" 

_dmenu() { 
    dmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray; 
}

main() {
  [ "$(printf "$NO\\n$YES" | _dmenu "$1" )" = "$YES" ] || exit 1 
}

_usage() { 
  echo "$ prompt [options] <Prompt>"
  echo ""
  echo "Yes/No prompt using dmenu."
  echo "Exits with value 0 if Yes and 1 if No."
  echo ""
  echo "options:"
  echo "  -h, --help      print this message"
  echo ""
  echo "Example:"
  echo "  $ ./prompt \"Do you want to shutdown?\" \\"
  echo "         && shutdown -h now || echo \"Dose not turn off\""
} 


# Read arguments
POSITIONAL=()
while [[ $# -gt 0 ]]; do
case $1 in
  -h|-?|--help) _usage; exit 0 ;;
  -*) echo "Invalid option '$1'" > /dev/stderr; exit 1 ;;
  *) POSITIONAL+=("$1") ;;
esac; shift;
done
main "${POSITIONAL[@]}"
