#!/bin/bash

options="-quality 98"
savepath="$HOME/LMedia/Pictures/"
preview="feh"

tmpimg=$(mktemp -u).png
savefile() {
    echo "$savepath"pic-"$(date '+%y%m%d-%H%M-%S').png"
}

echo $1
case $1 in 
    # TODO: area)
    win) import $options "$tmpimg" ;;
    curwin) import -window "$(get_winId)" "$tmpimg" ;;
    ""|root) import -window root $options "$tmpimg" ;;
esac


while true; do
    res="$(printf "quit\nsave\nsave as\npreview\ndragon" | dmenu -p "ScreenShot: ")"
    case "$res" in
        quit | "") break ;;
        save) cp "$tmpimg" "$(savefile)" ;;
        saveas) fp="$(echo $savepath | dmenu)" && cp "$tmpimg" "$fp" ;;
        dragon) dragon-drop --and-exit "$tmpimg" ;;
        preview) 
            [ -z "$child" ] && {
                i3-on_open --name 'feh' \
                    "floating enable;" \
                    "resize set 1400px 800px;" \
                    "move position center;" &

                feh -. "$tmpimg" &
                child="${!}";

                    
            } ;;
        # copy) 
    esac
done

# kill "$child"

rm "$tmpimg"

