#!/bin/sh

# Args:
PERMANENT=false

## Description
# use tmenu multiselect to delete files


main() {
    outf=$(mktemp)
    tmenu -ms <( ls "$@" ) $outf
    
    cat $outf | while read line; do
        if $PERMANENT; then  
            rm -- "${line}"
        else 
            gio trash "$line"
        fi 
    done 
    
    rm $outf 
}

list_file() {
    ls "$1"
}

_usage() { 
  echo "$0 [options]"
  echo "options:"
  echo "  -h, --help        print this message"
  echo "  -P, --permanent   delites the file(s) permanently"
}


# Read arguments
POSITIONAL=()
while [[ $# -gt 0 ]]; do
case $1 in
    -P|--permanent) PERMANENT=true ;;
    -h|-?|--help) _usage; exit 0 ;;
    -*) echo "Invalid option '$1'" > /dev/stderr; exit 1 ;;
    *) POSITIONAL+=("$1") ;;
esac; shift;
done
main "${POSITIONAL[@]}"
