#!/usr/bin/python3

import sys, os
import subprocess
from tempfile import mkdtemp
import json

def format(data):
    map = json.loads(open('/home/noko/.local/share/completions.json', 'r').read())
    for (v, k) in map.items():
        data = data.replace(k, f"\\{v}");
    return data;

def pdflatex(data, name):

    with open('tmp.tex', 'w') as f:
        f.write(data)

    os.system('pdflatex -synctex=1 -interaction=nonstopmode tmp.tex')
    for key in ['log', 'aux', 'pdf']:
        os.system('mv tmp.%s %s.%s' % (key, name, key))

    '''process = subprocess.Popen(["pdflatex"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    process.stdin.write(data.encode('utf8'))
    print(process.communicate()[0].decode('utf8'))
    process.stdin.close()'''


def main(args):
    texfile = args[1];
    name = '.'.join(texfile.split('.')[:-1]);

    data = None
    with open(texfile, 'r') as f:
        data = format(f.read());

    pdflatex(data, name);


if __name__ == "__main__":
    print(sys.argv)
    main(sys.argv)
