#!/bin/bash

yt-stream() {
    vlc "$(youtube-dl -x -g $1)" > /dev/null &
}

dmenu_choose() {

}

# random() {
#     selectedexpression=${expressions[$RANDOM % ${#expressions[@]} ]}
# }


% [ -z $1 ] dmenu_choose




