#!/bin/sh

yt_stream() {
    vlc "$(youtube-dl -x -g $1)" > /dev/null &
}

# random() {
#     selectedexpression=${expressions[$RANDOM % ${#expressions[@]} ]}
# }

main() {
    return 0
}


_usage() { 
    echo "ytpl - background YouTube music player"
    echo ""
    echo "Usage: ytpl [options] "
    echo ""
    # TODO echo " Description "
    echo "options: "
    echo "  -h      prints this message"
}

_invopt() {
    echo "Incorrect options provided '$1'"; usage; exit 1
}



# Read arguments
POSITIONAL=()
while [[ $# -gt 0 ]]; do
case $1 in
    -h|-?|--help) _usage ;;
    -*) _invopt ;;
    *) POSITIONAL+=("$1") ;;
esac; shift;
done
set -- "${POSITIONAL[@]}"

main "$@"
